### PR TITLE
fix(cli): --dry=fail should also fail when either added or removed typings

### PR DESCRIPTION
**Pull request by chelkyl**
Now correctly checks even if only added or only removed typings. Sorry for the bad logic in the original PR.

### CODE REVIEW

**Comment by jeffijoe** [comment]
The CI is failing due to Node 18 being the new `stable`, but not sure why?

**Comment by chelkyl** [comment]
Looks like the build config needs to be updated to choose a newer distribution than xenial.
See:
https://github.com/nodejs/node/issues/42351#issuecomment-1068424442
https://github.com/nodejs/node/blob/master/BUILDING.md#user-content-fn-6-8910fb58d5b6b09b4e9bdd3526f4717b

**Comment by jeffijoe** [comment]
I see, thanks! Would you mind updating the travis config in this PR? 😄

**Comment by chelkyl** [comment]
No problem! Updated to `focal` and it is passing all but `14`.
The build failure seems to be a network fluke or something because the error is [`read ECONNRESET`](https://app.travis-ci.com/github/jeffijoe/typesync/jobs/568316071#L260-L263).

**Comment by jeffijoe** [comment]
Nice, thanks! I’ll merge and release tomorrow, appreciate it!

**Pull request merged**
