### PR TITLE
Upgrade axios@0.19.0, fixs HTTP_PROXY use issue

### PR DESCRIPTION
**Pull request by septs**
Reference:
axios/axios#925

```text
➜  test git:(master) ✗ env | grep "PROXY"
HTTP_PROXY=http://127.0.0.1:6152
HTTPS_PROXY=http://127.0.0.1:6152
FTP_PROXY=http://127.0.0.1:6152
RSYNC_PROXY=http://127.0.0.1:6152
ALL_PROXY=http://127.0.0.1:6152
➜  test git:(master) ✗ # upgrade before
➜  test git:(master) ✗ time typesync
»  TypeSync v0.5.1
✖  Client network socket disconnected before secure TLS connection was established
Stack:
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:559:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1357:19)
    at Object.onceWrapper (events.js:291:20)
    at TLSSocket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
typesync  0.96s user 0.18s system 0% cpu 3:06.02 total
➜  test git:(master) ✗ # upgrade after
➜  test git:(master) ✗ time ../typesync/bin/typesync
»  TypeSync v0.5.1
✔  No new typings added, looks like you're all synced up!
../typesync/bin/typesync  0.13s user 0.02s system 6% cpu 2.329 total
```

### CODE REVIEW

**Comment by septs** [comment]
@jeffijoe Hope to release a patch version.

**Comment by jeffijoe** [comment]
Great! Will release when I get a chance!

**Comment by septs** [comment]
@jeffijoe When to release the next version?

**Comment by jeffijoe** [comment]
This has been released as 0.5.2, thanks!

**Pull request merged**
